## First steps

### First word

In [2]:
# Basic tool for communication with Python - print()
print('Hello')
print(42)
print('52/2 + 8')
print(52/2 + 8)

Hello
42
52/2 + 8
34.0


### Basic calculations with Python

In [5]:
# Addition & subtraction
print(4 + 7)
print(8 - 12)

# Multiplication & division
print(6 * 8)
print(24 / 3)

# Exponentiation
print(5 ** 3)

# Modulo - reminder of division
print(17 % 7)

11
-4
48
8.0
125
3


## Variables & Types

### Integer

In [6]:
# Integer type
length = 26
width = 4

# Print out variables
print(length, width)

26 4


In [8]:
# Calculation with variables
square = length * width
print(square)

104


In [9]:
# Type of variable
type(square)

int

### Float

In [40]:
# Fractional part of the number
integer = 6
print(integer, type(integer))

float_number = float(whole)
print(float_number, type(float_number))

6 <class 'int'>
6.0 <class 'float'>


In [41]:
# Result of division is float
two = 8 / 4
print(two)

2.0


### String

In [18]:
# String type
greeting = 'Hello'
type(greeting)

str

In [53]:
# Operations with strings - concatenation
double_greeting = greeting + greeting
print(double_greeting)

triple_greeting = greeting * 3
print(triple_greeting)

HelloHello
HelloHelloHello


### Boolean

In [20]:
# Boolean type
sunny = True
rainy = False

type(sunny), type(rainy)

(bool, bool)

In [24]:
# Operations with booleans
print(sunny + sunny)
print(rainy + sunny)
print(rainy + rainy)
print()
print(sunny * sunny)
print(rainy * sunny)
print(rainy * rainy)

2
1
0

1
0
0


### Types interactions

In [54]:
number = 2
items = 'apples'

print('Please, buy ' + str(number) + ' ' + items)

Please, buy 2 apples


## Lists

In [57]:
# Create a list
oranges = 1.99
tomatoes = 2.45
bread = 0.99
milk = 1.89

prices = [oranges, tomatoes, bread, milk]
print(prices)

[1.99, 2.45, 0.99, 1.89]


In [59]:
# Adapt list
prices = ['oranges', oranges,
         'tomatoes', tomatoes,
         'bread', bread,
         'milk', milk]
print(prices)

['oranges', 1.99, 'tomatoes', 2.45, 'bread', 0.99, 'milk', 1.89]


In [67]:
# List of lists
prices = [['oranges', oranges],
         ['tomatoes', tomatoes],
         ['bread', bread],
         ['milk', milk]]
print(prices)

[['oranges', 1.99], ['tomatoes', 2.45], ['bread', 0.99], ['milk', 1.89]]


In [69]:
# Subset list
print(prices[1])
print(prices[-1])
print(prices[1][1])

['tomatoes', 2.45]
['milk', 1.89]
2.45


In [72]:
# Calculation with list items
oranges_and_milk = prices[1][1] + prices[3][1]
print(oranges_and_milk)

4.34


In [89]:
# Slice list
prices = ['oranges', 1.99, 'tomatoes', 2.45, 'bread', 0.99, 'milk', 1.89]
print(prices[:2])
print(prices[2:6])
print(prices[6:])
print(prices[-4:])

['oranges', 1.99]
['tomatoes', 2.45, 'bread', 0.99]
['milk', 1.89]
['bread', 0.99, 'milk', 1.89]


In [90]:
# Change list items
prices[0] = 'peaches'
prices[-1] = 2.45
print(prices)

['peaches', 1.99, 'tomatoes', 2.45, 'bread', 0.99, 'milk', 2.45]


In [91]:
# Add list items
prices = prices + ['cheese', 4.55]
print(prices)

['peaches', 1.99, 'tomatoes', 2.45, 'bread', 0.99, 'milk', 2.45, 'cheese', 4.55]


In [93]:
# Delete list items
prices = ['peaches', 1.99, 'tomatoes', 2.45, 'bread', 0.99, 'milk', 2.45, 'cheese', 4.55]

del(prices[2:4])
print(prices)

del(prices[2:4])
print(prices)

['peaches', 1.99, 'bread', 0.99, 'milk', 2.45, 'cheese', 4.55]
['peaches', 1.99, 'milk', 2.45, 'cheese', 4.55]


In [95]:
# Copy lists
prices = ['peaches', 1.99, 'tomatoes', 2.45, 'bread', 0.99, 'milk', 2.45, 'cheese', 4.55]
prices_copy = prices[:]
print(prices)
print(prices_copy)

['peaches', 1.99, 'tomatoes', 2.45, 'bread', 0.99, 'milk', 2.45, 'cheese', 4.55]
['peaches', 1.99, 'tomatoes', 2.45, 'bread', 0.99, 'milk', 2.45, 'cheese', 4.55]


In [97]:
# Change new list
prices_copy[0] = 'apples'
print(prices_copy)
print(prices)

['apples', 1.99, 'tomatoes', 2.45, 'bread', 0.99, 'milk', 2.45, 'cheese', 4.55]
['peaches', 1.99, 'tomatoes', 2.45, 'bread', 0.99, 'milk', 2.45, 'cheese', 4.55]


## Functions & packages

### Built-in functions

In [100]:
# Functions with one argument
print(type('string'))
print(int(26.8))

<class 'str'>
26


In [103]:
# Functions with multiple arguments
number = 1/3
print(round(number))
print(round(number, 4))

0
0.3333


### String methods

In [106]:
# upper() and lower()
word = 'Stop'
print(word)

loud_word = word.upper()
print(loud_word)

quiet_word = word.lower()
print(quiet_word)

Stop
STOP
stop


In [111]:
# index() & count()
mood = 'optimistic'

print(mood.index('m'))
print(mood.count('o'))

4
1


### List methods

In [117]:
# index() & count()
fruits = ['apple', 'orange', 'pear', 'plum', 'ananas', 'orange', 'peach']

print(fruits.index('peach'))
print(fruits.count('orange'))

6
2


In [118]:
# append() 
fruits.append('mango')
print(fruits)

['apple', 'orange', 'pear', 'plum', 'ananas', 'orange', 'peach', 'mango']


In [123]:
# reverse() & sort()
print(fruits)
fruits.reverse()
print(fruits)

fruits.sort()
print(fruits)

['ananas', 'apple', 'mango', 'orange', 'orange', 'peach', 'pear', 'plum']
['plum', 'pear', 'peach', 'orange', 'orange', 'mango', 'apple', 'ananas']
['ananas', 'apple', 'mango', 'orange', 'orange', 'peach', 'pear', 'plum']


### Packages

#### math

In [134]:
# pi
from math import pi
r = 4.2
s = pi * r**2
print(s)

55.41769440932395


In [135]:
# factorial
from math import factorial
print(factorial(8))

40320


#### numpy

In [144]:
# Difference between lists and arrays
import numpy as np

list_of_numbers = [1, 6, 2, 9]
array_of_numbers = np.array(list_of_numbers)

print(list_of_numbers * 2)
print(array_of_numbers * 2)
print()

another_list = [4.2, 5.1, 7.1, 1.8]
another_array = np.array(another_list)

print(list_of_numbers + another_list)
print(array_of_numbers + another_array)
print()

# list_of_numbers * another_list gives TypeError
print(array_of_numbers * another_array)

[1, 6, 2, 9, 1, 6, 2, 9]
[ 2 12  4 18]

[1, 6, 2, 9, 4.2, 5.1, 7.1, 1.8]
[ 5.2 11.1  9.1 10.8]

[ 4.2 30.6 14.2 16.2]


In [165]:
# Sort arrays
numbers = np.array([3, 5, 5, 4, 4, 7, 3, 2, 1, 1, 8, 6])
print(numbers)
print(numbers[numbers < 3])
print(numbers[numbers > 5])

[3 5 5 4 4 7 3 2 1 1 8 6]
[2 1 1]
[7 8 6]


In [168]:
# Subset arrays
print(numbers)
print(numbers[1])
print(numbers[:4])
print(numbers[5:8])

[3 5 5 4 4 7 3 2 1 1 8 6]
5
[3 5 5 4]
[7 3 2]


In [171]:
# 2D numpy arrays
matrix = np.array([[10, 7.4],[15, 12.7],[21, 9.5],[18, 7.5]])
print(matrix)
print()
print(matrix.shape)

[[10.   7.4]
 [15.  12.7]
 [21.   9.5]
 [18.   7.5]]

(4, 2)


In [176]:
# Basic statistic with numpy
print(numbers)

mean = np.mean(numbers)
print("Average: " + str(mean))

median = np.median(numbers)
print("Median: " + str(median))

std = np.std(numbers)
print("Standard deviation: " + str(std))

[3 5 5 4 4 7 3 2 1 1 8 6]
Average: 4.083333333333333
Median: 4.0
Standard deviation: 2.1392496088322392
